### POST ORDERS
POST http://localhost:8000/order-service/3b9877f6-cb57-4801-b1e3-19bc61025fa2/orders
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzYjk4NzdmNi1jYjU3LTQ4MDEtYjFlMy0xOWJjNjEwMjVmYTIiLCJleHAiOjE2MzAwNjA1MTZ9.lbflmq-0bVLUgZM-hz5tkzWboX-rhmbLvfhJt9XMhGKcHGYC8FgO_prfXW1rVYJCRfcjX2cifj9sjsRcYUyj8g
Content-Type: application/json

{
  "productId" : "CATALOG-002",
  "qty" : 30,
  "unitPrice" : 1500
}

### GET ORDERS
GET http://localhost:8000/order-service/3b9877f6-cb57-4801-b1e3-19bc61025fa2/orders